package SalamiEvaluator.types.ast;

public enum NodeType {
    AST,
    BINARYEXPRESSION,
    EXPRESSION,
    PROGRAM,
    STATEMENT,
    VARIABLEDECLARATIONSTATEMENT,
    NUMERICALLITERAL,
    STRINGLITERAL,
    FLOATINGPOINTLITERAL,
    IDENTIFIER,
    COMMENT,
    VOIDLITERAL,
}
